'use strict';

/**
 * PBIX table name → SQL Server view name.
 * Source: "Table Source" sheet in the RTB Dataverse Technical Document.
 * Only data tables (not "Measure Table", "Manual Table", or "DAX Table").
 */
const TABLE_MAP = {
  'Pipeline': 'vw_TF_EBI_P2S',
  'Region Hierarchy': 'vw_TD_EBI_REGION_RPT',
  'Sales Stage': 'vw_EBI_SALES_STAGE',
  'Snapshot Quarter': 'vw_EBI_Caldate',
  'Close Quarter': 'vw_EBI_Caldate',
  'Close Quarter JOIN': 'vw_EBI_Caldate',
  'Closure Quarter': 'vw_EBI_Caldate',
  'Qualification Quarter': 'vw_EBI_Caldate',
  'Create Quarter': 'vw_EBI_Caldate',
  'Renewal Quarter': 'vw_EBI_Caldate',
  'Delivery Quarter': 'vw_EBI_Caldate',
  'Deal Review Quarter': 'vw_EBI_Caldate',
  'Opp Close Quarter': 'vw_EBI_Caldate',
  'Service End Quarter': 'vw_EBI_Caldate',
  'FY Calendar': 'vw_EBI_Caldate',
  'Snapshot Switch Quarter': 'vw_EBI_Caldate',
  'Snapshot Month Join': 'vw_EBI_Caldate',
  'Quota': 'vw_TF_EBI_QUOTA',
  'Retention': 'vw_TF_EBI_Retention',
  'Retention MetaData': 'vw_TD_EBI_Retention_MetaData',
  'Retention Snapshot Type': 'vw_TD_EBI_RETENTION_SNAPSHOT_TYPE',
  'Renewals Target': 'vw_TF_EBI_RENEWALS_TARGET',
  'Pipe Walk': 'vw_TF_EBI_PIPE_WALK',
  'TPT': 'vw_TF_EBI_TPT_INFO',
  'TPT Metadata': 'vw_TD_EBI_TPT_INFO',
  'TPT COMPETITOR': 'vw_TD_EBI_TPT_COMPETITORS',
  'Account': 'vw_TD_EBI_ACCOUNT',
  'Account ARR': 'vw_TF_EBI_ACC_OPG_ARR',
  'Account Sub': 'vw_TD_EBI_SUB',
  'Account Parent': 'vw_TD_EBI_PRNT',
  'Account Country': 'vw_TD_EBI_ACCOUNT_COUNTRY',
  'Account Engagement Stage': 'vw_TD_EBI_AES_SCORE',
  'Account Activities': 'vw_TF_EBI_REP_ACTIVITY',
  'Account Activities Metadata': 'vw_TD_EBI_REP_ACTIVITY',
  'Account Activities Doc Metadata': 'vw_TD_EBI_REP_ACTIVITY_DOC',
  'Account Sub Market Area Metadata': 'vw_TD_EBI_SUB_MA_METADATA',
  'Account Sub Market Area Solution Metadata': 'vw_TD_EBI_SUB_MA_SOLUTION_METADATA',
  'AE Region Hierarchy': 'vw_TD_EBI_AE_REGION',
  'Enablement': 'vw_EBI_EMP_ENABLEMENT',
  'Enablement Category': 'vw_EBI_ENABLEMENT_CATEGORY',
  'Generation Target Multipliers': 'TF_EBI_GENERATION_TARGET',
  'Pacing Targets': 'vw_EBI_PACING_TARGET',
  'TM1 Bookings': 'vw_TF_EBI_BOOKINGS',
  'Product Consumption': 'vw_TF_EBI_PRODUCT_USAGE',
  'Product Consumption Metadata': 'vw_TF_EBI_PRODUCT_USAGE_METADATA',
  'Product Consumption Category': 'vw_TD_EBI_UsageCategory',
  'SBR Activities': 'vw_TF_EBI_SBR_ACTIVITIES',
  'SBR Metadata': 'vw_TD_EBI_SBR_ACTIVITIES',
  'Deal Type': 'vw_EBI_DEAL_TYPE',
  'Deal Band': 'vw_TD_EBI_DEAL_BAND',
  'Commit Type': 'vw_EBI_COMMIT_ROLE_MAPPING',
  'Commit Type RLS': 'vw_TD_EBI_RLS_BY_COMMIT_ROLE_TYPE',
  'Target Type': 'vw_TD_EBI_TARGET_TYPE',
  'Segment': 'vw_EBI_SEGMENT',
  'Opportunity': 'vw_TD_EBI_OPP',
  'OPG': 'vw_EBI_OPG',
  'Creator Type': 'vw_EBI_CREATOR_TYPE',
  'Revenue Type': 'vw_EBI_REVENUE_TYPE',
  'Sales Motion': 'vw_TD_EBI_SALES_MOTION',
  'Sales Play': 'vw_TD_EBI_SALES_PLAY',
  'Pay Measure': 'vw_EBI_PAY_MEASURE',
  'GTM Motion': 'vw_EBI_GTM_MOTION',
  'Opp Driver': 'vw_EBI_OPP_DRIVER',
  'Partner Created': 'vw_EBI_PARTNER_CREATED',
  'Partner Metadata': 'vw_EBI_PARTNER',
  'Upsell Type': 'vw_TD_EBI_UPSELL_TYPE',
  'Customer Health': 'vw_TD_EBI_CUSTOMER_HEALTH',
  'Customer Solution Health': 'vw_TD_EBI_CUSTOMER_SOLUTION_HEALTH',
  'Customer Health Movement': 'vw_TF_EBI_CUSTOMER_HEALTH_MOVEMENT',
  'Customer Solution Health Movement': 'vw_TF_EBI_CUSTOMER_SOLUTION_HEALTH_MOVEMENT',
  'Customer Profile Attributes': 'vw_TD_ICP_UCP_SCORES',
  'Health Movement Metadata': 'vw_TD_EBI_CUSTOMER_HEALTH_MOVEMENT',
  'Reporting Hierarchy': 'VW_TD_EBI_REPORTING_HIERARCHY',
  'Consulting Segment': 'vw_EBI_CONSULTING_SEGMENT',
  'Focus Vertical': 'vw_EBI_FOCUS_VERTICAL',
  'Emp Ldap Geo Title': 'vw_TD_EBI_EMP_LDAP_NAME',
  'App Inputs': 'vw_EBI_SELLER_APP_INPUTS',
  'Plan & QRF': 'vw_TF_EBI_PLAN_RPT',
  'DRF Pillars': 'vw_EBI_DRF_PILLARS',
  'SalesRegion': 'vw_TD_EBI_REP_ACCESS_RLS',
  'SalesTeam': 'vw_TD_EBI_REP_ACCESS_RLS',
  'SalesRegion_Overlay': 'vw_TD_EBI_REP_ACCESS_RLS',
  'SalesTeam_Overlay': 'vw_TD_EBI_REP_ACCESS_RLS',
  'Overlay_SR': 'vw_TD_EBI_REP_ACCESS_RLS',
  'Overlay_ST': 'vw_TD_EBI_REP_ACCESS_RLS',
  'vw_EBI_PROJECTION_CLOSE_RATIO': 'vw_EBI_PROJECTION_CLOSE_RATIO',
  'vw_TD_EBI_REP_ACCESS_RLS': 'vw_TD_EBI_REP_ACCESS_RLS',
  'vw_TF_EBI_P2S_LATEST_ATTRIBUTE': 'vw_TF_EBI_P2S_LATEST_ATTRIBUTE',
  'Daily Weekly Switch': null, // Manual table — no SQL equivalent
  'Logged In User Role': null, // Manual table
  'Is Consumption Primary Metric': null, // DAX calculated table
  'Segment AVG days Business Issue budget Mutual': null, // DAX table
  'OCC_Performance Cohort_Band': null, // Unmapped OCC table
  'OCC_Performance Cohort FLM_Band': null, // Unmapped OCC table
};

/**
 * Short alias for table names used in SQL (for FROM/JOIN clauses).
 */
const TABLE_ALIAS = {
  'vw_TF_EBI_P2S': 'p',
  'vw_TD_EBI_REGION_RPT': 'rh',
  'vw_EBI_SALES_STAGE': 'ss',
  'vw_EBI_Caldate': 'cal',
  'vw_TF_EBI_QUOTA': 'q',
  'vw_TF_EBI_Retention': 'ret',
  'vw_TF_EBI_RENEWALS_TARGET': 'rt',
  'vw_TF_EBI_PIPE_WALK': 'pw',
  'vw_TF_EBI_TPT_INFO': 'tpt',
  'vw_TD_EBI_TPT_INFO': 'tptm',
  'vw_TF_EBI_ACC_OPG_ARR': 'arr',
  'vw_EBI_EMP_ENABLEMENT': 'en',
  'TF_EBI_GENERATION_TARGET': 'gt',
  'vw_EBI_PACING_TARGET': 'pt',
  'vw_TF_EBI_BOOKINGS': 'bk',
  'vw_TF_EBI_PRODUCT_USAGE': 'pu',
  'vw_TF_EBI_SBR_ACTIVITIES': 'sbr',
  'vw_TF_EBI_REP_ACTIVITY': 'act',
  'vw_EBI_DEAL_TYPE': 'dt',
  'vw_EBI_COMMIT_ROLE_MAPPING': 'cm',
  'vw_TD_EBI_TARGET_TYPE': 'tt',
  'vw_EBI_SEGMENT': 'seg',
  'vw_TD_EBI_OPP': 'opp',
  'vw_EBI_OPG': 'opg',
  'vw_TD_EBI_ACCOUNT': 'acct',
  'vw_TD_EBI_SUB': 'sub',
  'vw_TD_EBI_PRNT': 'prnt',
  'vw_TF_EBI_PLAN_RPT': 'plan',
  'VW_TD_EBI_REPORTING_HIERARCHY': 'rpt',
  'vw_TD_EBI_AES_SCORE': 'aes',
  'vw_TD_EBI_ACCOUNT_COUNTRY': 'ctry',
};

/** PBIX measure table → glossary section. */
const SECTION_MAP = {
  '_Pipeline Measures': 'Pipeline',
  '_Performance Measures': 'Performance & Participation',
  '_TPT Measures': 'Territory Planning (TPT)',
  '_Generation Target Measures': 'Pipeline Creation',
  '_Target Measures': 'Forecast & Bookings',
  '_Retention Measures': 'Retention',
  '_Walk Measures': 'Pipe Walk',
  '_Coverage Measures': 'Pipeline Coverage',
  '_OCC Measures': 'SLM Performance',
  '_Retention Target Measures': 'Retention',
  'Region Hierarchy': 'Performance & Participation',
  '_Enablement Measures': 'Enablement',
  '_Account ARR Measures': 'ARR & Revenue',
  '_SBR Measures': 'SBR / Account Activity',
  '_Account Activity Measures': 'SBR / Account Activity',
  '_Product Consumption': 'Product Consumption',
  '_TM1 Booking Measures': 'Forecast & Bookings',
  'Snapshot Quarter': 'Pipeline',
};

/** Measures to exclude (presentational / non-data). */
const EXCLUDED_MEASURES = new Set([
  'DEFAULT COMMIT TYPE',
  'DEFAULT TARGET TYPE',
  'Last Data Refresh',
  'Dynamic Drillthrough page',
  'Action Path',
  'Cohort',
]);

/** Abbreviation expansions for alias generation. */
const ABBREVIATIONS = {
  'QTD': 'quarter to date',
  'YTD': 'year to date',
  'WTD': 'week to date',
  'CQ': 'current quarter',
  'PQ': 'previous quarter',
  'BOQ': 'beginning of quarter',
  'CY': 'current year',
  'FY': 'fiscal year',
  'W+F+UC': 'won forecast upside committed',
  'GPC': 'gross pipeline created',
  'SS5+': 'sales stage 5 plus',
  'S3': 'sales stage 3',
  'S4': 'sales stage 4',
  'S5+': 'sales stage 5 plus',
  'S1\\S2': 'sales stage 1 and 2',
  'ASV': 'annual subscription value',
  'ARR': 'annual recurring revenue',
  'GNARR': 'gross net annual recurring revenue',
  'OPG': 'opportunity group',
  'FLM': 'first line manager',
  'REP': 'representative',
  'SBR': 'strategic business review',
  'TPT': 'territory plan tracker',
  'DRF': 'deal review framework',
  'RBOB': 'renewal base of business',
  'LTG': 'left to go',
  'COV': 'coverage',
  'GC': 'gross creation',
  'TM1': 'TM1 booking system',
  'EOQ': 'end of quarter',
  'OCC': 'one command center',
  'PRNT': 'parent',
  'SUB': 'subsidiary',
  'ACCTS': 'accounts',
  'OPPTY': 'opportunity',
  'OPP': 'opportunity',
};

module.exports = {
  TABLE_MAP,
  TABLE_ALIAS,
  SECTION_MAP,
  EXCLUDED_MEASURES,
  ABBREVIATIONS,
};
